# Generated by Django 5.1.4 on 2025-01-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cartmodel_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
